### ISSUE TITLE
Implement signin/login with google

### ISSUE THREAD

**Issue by ShivamMadlani** [ShivamMadlani/chatApp#5]
#### Issue Description:

**Problem:**
Currently, our application lacks the ability to allow users to sign in or log in using their Google accounts. This feature is increasingly important for user convenience and security.

**Proposed Solution:**
We should implement Google Sign-In functionality to streamline the user onboarding process and provide users with a secure and convenient authentication option.

#### Tasks:

1. **Google API Integration:**
   - Integrate the Google Sign-In API to allow users to sign in with their Google accounts.
   - Set up OAuth 2.0 authentication with Google services.

2. **User Interface:**
   - Design and implement the user interface components for Google Sign-In.
   - Ensure the user has the option to sign in with their Google account on the login or registration page.

3. **Backend Changes:**
   - Create endpoints or controllers to handle Google Sign-In requests.
   - Implement the server-side logic to verify and process Google authentication tokens.

4. **User Data Handling:**
   - Map Google user data to our application's user profiles.
   - Store relevant user data securely in our database.

5. **Testing:**
   - Conduct thorough testing to ensure the feature works as expected.
   - Test different scenarios, including successful sign-ins, error handling, and user data retrieval.

#### Additional Considerations:

- Ensure the user's privacy and data security are maintained throughout the Google Sign-In process.
- Handle scenarios where a user revokes the application's access to their Google account.
- Implement error handling and user-friendly error messages for various scenarios.

#### Labels:
- enhancement
- authentication
- Google Sign-In

#### Additional Information:
Sample app: https://www.passportjs.org/tutorials/google/
Blog: https://medium.com/@prashantramnyc/how-to-implement-google-authentication-in-node-js-using-passport-js-9873f244b55e
.

**Comment by mismathh** [comment]
Hi, there! I would like to tackle this issue.

**Comment by ShivamMadlani** [comment]
Go ahed.. give it a try

**Comment by mismathh** [comment]
How does this look?
![Google button](https://github.com/ShivamMadlani/chatApp/assets/91957448/48be1d37-dace-4079-8861-549493e4594d)

**Comment by ShivamMadlani** [comment]
this looks good...
nice work 👍
