### ISSUE TITLE
Fix time displayed under messages

### ISSUE THREAD

**Issue by ShivamMadlani** [ShivamMadlani/chatApp#6]
#### Issue Description:

**Problem:**
Currently, the time displayed under messages in our application is not being rendered correctly. This issue is created to track the resolution of the time display problem.

**Proposed Solution:**
We need to address the issues with time display under messages and ensure that the timestamps are accurate and consistent.

**Proposed approach**
We could use an inbuilt object of javascript i.e. Date() to find out current day and time. We can then subtract the date at which message was sent to find the difference and display appropriately how many days ago a message was sent. i.e. yesterday or monday etc.

#### Tasks:

1. **Timestamp Formatting:**
   - Review the code responsible for rendering message timestamps.
   - Ensure that timestamps are consistently formatted and displayed in a user-friendly way.

2. **Real-Time Updates:**
   - Implement a mechanism to update message timestamps in real-time.
   - Utilize appropriate libraries or technologies to achieve this.

3. **Testing:**
   - Conduct thorough testing to confirm that the time display issue has been resolved.
   - Verify that timestamps are accurate and consistently displayed.

#### Additional Considerations:

- Consider time zone handling to ensure that timestamps are displayed accurately for users in different time zones.
- Address any related visual inconsistencies or alignment issues in the message display.

#### Labels:
- bug
- user interface
- real-time updates

**Comment by bhavik001** [comment]
Hey @ShivamMadlani 
Can you assign me this issue 
I am interested in working on it.

**Comment by ShivamMadlani** [comment]
Go ahed

**Comment by bhavik001** [comment]
Hey @ShivamMadlani 
Can you please merge the pull request?

**Comment by bhavik001** [comment]
Hey @ShivamMadlani 
Can you please merge the pull request?

**Comment by ShivamMadlani** [comment]
hey @bhavik001 left a code review... make the change and will merge

**Comment by bhavik001** [comment]
Hey @ShivamMadlani 
I have push the code. Let me know what I have to change. as I cannot see any review on the pull request.

**Comment by ShivamMadlani** [comment]
youll be able to see the review under ur pull request

**Comment by bhavik001** [comment]
Hey 
Now I have updated the file. Pleas take a look.
